import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
    const [lang, setLang] = useState(localStorage.getItem('app_language') || 'uz');

    const changeLang = (newLang) => {
        localStorage.setItem('app_language', newLang);
        setLang(newLang);
    };

    return (
        <LanguageContext.Provider value={{ lang, changeLang }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLang() {
    return useContext(LanguageContext);
}

export const translations = {
    uz: {
        // Navbar
        dashboard:    'Dashboard',
        vocabulary:   "Lug'at",
        statistics:   'Statistika',
        tests:        'Testlar',
        ai:           'AI Tutor',
        profile:      'Profil',
        settings:     'Sozlamalar',
        logout:       'Chiqish',
        notifications:'Bildirishnomalar',
        // Settings
        language:     'Til',
        save:         'Saqlash',
        saved:        '✅ Sozlamalar saqlandi!',
        deleteAcc:    "Akkauntni o'chirish",
        deleteDesc:   "Bu amalni qaytarib bo'lmaydi",
        delete:       "O'chirish",
        dangerZone:   '⚠️ Xavfli zona',
        emailNotif:   'Email bildirishnomalar',
        emailDesc:    'Yangi testlar va natijalar haqida',
        telegramNotif:'Telegram bildirishnomalar',
        telegramDesc: 'Bot orqali xabar olish',
        dailyReminder:'Kunlik eslatmalar',
        dailyDesc:    "Har kuni o'qishga undash",
        // Dashboard
        hello:        'Salom',
        dailyStreak:  'Kunlik streak',
        streakDays:   'kun ketma-ket',
        dailyGoal:    'Kunlik maqsad',
        done:         '✅ Bajarildi!',
        remaining:    (n) => `${n} ta qoldi`,
        xpUntil:      (n) => `${n} XP gacha`,
        maxLevel:     'Max level! 🏆',
        myResults:    'Natijalarim',
        testsCount:   (n) => `${n} ta test`,
        aiServices:   'AI Xizmatlar',
        aiTeacher:    'AI Muallim',
        aiTeacherSub: 'Essay tekshiruv, speaking mashq, grammatika — istalgan vaqt istalgan mavzu',
        startChat:    'Suhbat boshlash',
        sections:     "Bo'limlar",
        vocabSub:     "So'zlarni saqlash va takrorlash",
        statsSub:     'Progress va zaif tomonlar',
        testsSub:     'Mock testlarni boshlash',
        levelTitles:  ['Beginner', 'Beginner+', 'Intermediate', 'Advanced', 'Expert'],
        dailyPlan:    'Kunlik Reja',
        dailyPlanSub: "AI sizga shaxsiy reja tuzadi",
        // Common
        back:         '← Orqaga',
        cancel:       'Bekor qilish',
        error:        'Xatolik yuz berdi',
        loading:      'Yuklanmoqda...',
        saving:       'Saqlanmoqda...',
        noData:       "Hali ma'lumot yo'q",
        // Vocabulary Page
        vocabTitle:   "📚 Lug'at",
        wordsCount:   (n) => `${n} ta so'z saqlangan`,
        addWord:      "➕ So'z qo'shish",
        allWords:     (n) => `📖 Barcha so'zlar (${n})`,
        flashcardTab: '🔄 Flashcard',
        searchPlaceholder: "🔍 So'z yoki tarjima bo'yicha qidirish...",
        wordNotFound: 'Topilmadi',
        noWordsYet:   "Hali so'z yo'q",
        tryOtherWord: 'Boshqa so\'z bilan qidiring',
        addFirstWord: '"So\'z qo\'shish" tugmasini bosing',
        wordAdded:    "✅ So'z qo'shildi!",
        wordDeleted:  "🗑️ So'z o'chirildi",
        confirmDelete:"Bu so'zni o'chirishni istaysizmi?",
        errorOccurred:'❌ Xatolik yuz berdi',
        // Flashcard
        flipCard:     "Kartani bosing — tarjimani ko'ring",
        howWell:      'Qanchalik yaxshi bildingiz?',
        clickToFlip:  'bosing →',
        translation:  'Tarjima',
        rateUnknown:  'Bilmadim',
        rateHard:     'Qiyin',
        rateRemember: 'Esladim',
        rateEasy:     'Oson!',
        skipCard:     "O'tkazib yuborish →",
        reviewDone:   (n) => `${n} ta so'z takrorlandi!`,
        reviewAgain:  '🔄 Qaytadan',
        reviewAll:    "📖 Hammasini takrorla",
        // Review options
        todayReview:  '🔔 Bugungi takrorlash',
        todayReviewSub: "SM-2 algoritmi bo'yicha takrorlash vaqti kelgan so'zlar",
        startReview:  (n) => `Boshlash (${n} ta)`,
        noReviewDue:  "Hozircha tayyor so'z yo'q",
        reviewAllWords: "📖 Barcha so'zlarni takrorlash",
        reviewAllSub: "Lug'atdagi barcha so'zlarni flashcard sifatida o'rganish",
        reviewAllBtn: (n) => `Hammasini takrorla (${n} ta)`,
        noWordsToReview: "Hali so'z yo'q",
        // Add word modal
        newWord:      '➕ Yangi so\'z',
        wordEng:      "So'z (inglizcha) *",
        wordTranslation: 'Tarjima *',
        exampleSentence: 'Misol jumla (ixtiyoriy)',
        wordRequired: "So'z va tarjima majburiy!",
        addError:     "Xatolik yuz berdi. Qaytadan urinib ko'ring.",
        // Statistics Page
        statsTitle:   '📊 Statistika',
        statsSub2:    'Progressingiz va zaif tomonlaringiz',
        overallBand:  'Umumiy Band Score',
        bySection:    "Bo'limlar bo'yicha",
        weakAreas:    '⚠️ Zaif tomonlar',
        practiceMore: "Quyidagi bo'limlar bo'yicha ko'proq mashq qiling:",
        tipLabel:     '💡 Tavsiya:',
        tipText:      "Zaif bo'limlar bo'yicha kunida kamida 1 ta test ishlang.",
        noWeakAreas:  "Zaif tomonlar yo'q!",
        allAbove6:    "Barcha bo'limlarda 6.0 dan yuqori ball to'plangansiz.",
        noTestsYet:   'Hali hech qanday test topshirilmagan. Statistika test ishlangandan keyin ko\'rinadi.',
        lastResults:  "📋 So'nggi natijalar",
        noChartData:  "Hali ma'lumot yo'q",
        testsLabel:   (n) => `${n} ta test`,
        // Tests Page
        mockTests:    'Mock Testlar',
        mockTestsSub: "Bo'limni tanlang va testni boshlang",
        startBtn:     'Boshlash →',
        minutes:      (n) => `${n} daqiqa`,
        questions:    (n) => `${n} savol`,
        noTests:      "Bu bo'limda hali testlar yo'q",
        testDesc:     'Test topshiriq va savollardan iborat',
        comingSoon:   "Bu bo'lim tez orada qo'shiladi!",
        // Profile Page
        profileTitle: 'Profil',
        personalInfo: "Shaxsiy ma'lumotlar",
        editBtn:      '✏️ Tahrirlash',
        cancelEdit:   'Bekor qilish',
        saveBtn2:     '💾 Saqlash',
        phoneLabel:   'Telefon',
        notEntered:   'Kiritilmagan',
        dataSaved:    "Ma'lumotlar saqlandi!",
        subscription: 'Obuna',
        freePlan:     '🆓 Bepul tarif',
        premiumPlan:  '⭐ Premium tarif',
        limitedFeats: 'Cheklangan imkoniyatlar',
        allFeats:     'Barcha imkoniyatlar ochiq',
        upgradePrem:  "⚡ Premium ga o'tish",
        // AI Chat Page
        aiQuickTitle: '🚀 Tezkor savollar',
        aiInfoTitle:  '🤖 AI Tutor',
        aiInfoText:   "Claude AI asosida ishlaydi. IELTS bo'yicha barcha savollarga javob beradi.",
        aiClearBtn:   '🗑 Tozalash',
        aiChatTitle:  '🎓 AI IELTS Tutor',
        aiPlaceholder:"Savolingizni yozing... (Enter — yuborish, Shift+Enter — yangi qator)",
        aiNewChat:    'Yangi suhbat boshlandi! Qanday yordam kerak?',
        aiNetError:   "⚠️ Xatolik yuz berdi. Internet aloqangizni tekshiring va qayta urinib ko'ring.",
        aiWelcome:    "Salom! Men sizning IELTS tutoryingizman 🎓\n\nMenga quyidagilarni so'rashingiz mumkin:\n• Writing esse tekshiruv va maslahatlar\n• Speaking mashq savollari\n• Grammatika tushuntirish\n• IELTS band scoring mezonlari\n• Vocabulary kengaytirish\n\nBoshlaylik! Qanday yordam kerak?",
        aiQuick1:     'Writing Task 2 uchun maslahat ber',
        aiQuick2:     'Band 7 olish uchun nima qilish kerak?',
        aiQuick3:     'Speaking Part 2 qanday tayyorlaniladi?',
        aiQuick4:     'Mening esseni tekshir',
        // Daily Plan Page
        dpHeroTitle:  "Shaxsiy O'quv Rejangiz",
        dpHeroSub:    "AI sizning darajangizga mos, maqsadli reja tuzib beradi.\nMuddatni tanlang va boshlang.",
        dpSkillLabel: "Ko'nikma yo'nalishi",
        dpDurLabel:   "Reja muddatini tanlang",
        dpGenBtn:     "AI Reja Tuzsin",
        dpGenHint:    "Reja yaratish uchun yuqoridan muddat tanlang",
        dpLoadTitle:  "AI reja tuzmoqda...",
        dpLoadSub:    "Sizning darajangizga mos reja tayyorlanmoqda",
        dpBackBtn:    "← Orqaga",
        dpAiBadge:    "✦ AI tomonidan yaratilgan",
        dpTotalTasks: "Jami vazifa",
        dpEstTime:    "Taxminiy vaqt",
        dpSkillTypes: "Ko'nikma turi",
        dpTasksTitle: "Vazifalar ro'yxati",
        dpTasksHint:  "(bajarganingizda ustiga bosing ✓)",
        dpNewPlan:    "🔄 Yangi reja yaratish",
        dpGoTests:    "📝 Testlarga o'tish →",
        dpErrorMsg:   "Reja yaratishda xatolik yuz berdi. Qaytadan urinib ko'ring.",
        dpDur1Label:  "1 Kunlik Reja",
        dpDur1Sub:    "Bugungi uchun tez va samarali reja",
        dpDur2Label:  "1 Haftalik Reja",
        dpDur2Sub:    "7 kunlik bosqichma-bosqich o'quv yo'li",
        dpDur3Label:  "1 Oylik Reja",
        dpDur3Sub:    "To'liq IELTS tayyorgarlik dasturi",
        dpSkillAll:   "Hammasi",
        // AIDailyPlanWidget
        widgetTitle:    "Kunlik O'quv Reja",
        widgetMorning:  "Ertalabki reja",
        widgetAfternoon:"Kunduzgi reja",
        widgetEvening:  "Kechki reja",
        widgetSub:      "AI sizga shaxsiy reja tuzadi",
        widgetCompact:  "📋 Reja yaratish",
        // Pricing Page
        pricingTitle:   'Narxlar',
        pricingSubtitle:'Maqsadingizga mos tarifni tanlang',
        pricingPopular: '⭐ Mashhur',
        pricingPerMonth:'UZS/oy',
        pricingFreeFeatures: [
            '✅ 3 ta mock test',
            "✅ Lug'at moduli",
            '✅ Statistika',
            '✅ Telegram bot',
            '❌ AI baholash',
            '❌ Cheksiz testlar',
            '❌ Shaxsiy reja',
        ],
        pricingPremiumFeatures: [
            '✅ Cheksiz mock testlar',
            '✅ AI Writing baholash',
            '✅ AI Speaking baholash',
            "✅ Shaxsiy o'quv rejasi",
            '✅ Telegram bot',
            '✅ Statistika va tahlil',
            "✅ Lug'at moduli",
        ],
        pricingFreeBtn:    'Boshlash',
        pricingPremiumBtn: 'Premium olish',
        pricingFaqTitle:   "Ko'p so'raladigan savollar",
        pricingFaq: [
            { q: "To'lov qanday amalga oshiriladi?", a: "Click yoki Payme orqali to'lash mumkin." },
            { q: "Obunani bekor qilish mumkinmi?", a: "Ha, istalgan vaqtda bekor qilish mumkin." },
            { q: "Bepul versiyada qancha test bor?", a: "Bepul versiyada 3 ta mock test mavjud." },
        ],
        // Landing Page
        landingNavPricing:  'Narxlar',
        landingNavLogin:    'Kirish',
        landingNavRegister: 'Bepul boshlash →',
        landingHeroWords:   ["Band 7+", "Band 8+", "Muvaffaqiyat", "Yuqori ball"],
        landingHeroTitle:   "olishga tayyor bo'ling",
        landingHeroSub:     "AI baholash, mock testlar, shaxsiy o'quv rejasi —\nbarchasi bitta platformada. O'zbek tilida. 🇺🇿",
        landingHeroBtn:     'Bepul boshlash →',
        landingHeroLogin:   'Kirish',
        landingStats: [
            { num: '50+', label: 'Faol foydalanuvchi' },
            { num: '4',   label: "IELTS bo'limi" },
            { num: 'AI',  label: 'Baholash tizimi' },
            { num: '24/7',label: 'Ishlaydi' },
        ],
        landingPathTitle:   "Sizning yo'lingiz",
        landingPathSub:     'Har bir darajada nima qilish kerakligini bilib oling',
        landingBands: [
            { band: '5.0', label: "Boshlang'ich", color: '#ef4444' },
            { band: '6.0', label: "O'rta",        color: '#f59e0b' },
            { band: '7.0', label: 'Yaxshi',       color: '#10b981' },
            { band: '8.0', label: 'Ajoyib',       color: '#3b82f6' },
            { band: '9.0', label: 'Expert',       color: '#8b5cf6' },
        ],
        landingFeatTitle: 'Nima imkoniyatlar bor?',
        landingFeatSub:   'Maqsadingizga yetish uchun kerak bo\'lgan hamma narsa',
        landingFeatures: [
            { icon: '🧠', title: 'AI Baholash',    desc: "Writing va Speaking uchun sun'iy intellekt baholash" },
            { icon: '📝', title: 'Mock Testlar',   desc: "Reading, Listening, Writing, Speaking — 4 bo'lim" },
            { icon: '📊', title: 'Statistika',     desc: 'Band score tarixi va zaif tomonlarni tahlil qilish' },
            { icon: '📅', title: 'Shaxsiy Reja',  desc: "Har bir foydalanuvchi uchun alohida o'quv rejasi" },
            { icon: '📚', title: "Lug'at",         desc: "Spaced repetition bilan so'z yodlash" },
            { icon: '🤖', title: 'Telegram Bot',  desc: 'Istalgan joyda mashq qilish imkoniyati' },
        ],
        landingTestimonialsTitle: 'Foydalanuvchilar nima deydi?',
        landingTestimonials: [
            { name: 'Ali X.',     score: '7.5', text: "3 oyda bandimni 5.5 dan 7.5 ga chiqardim!", flag: '🇺🇿' },
            { name: 'Nozima B.', score: '8.0', text: "AI feedback juda aniq va foydali bo'ldi.",   flag: '🇺🇿' },
            { name: 'Malika T.', score: '7.0', text: "Speaking testlari menga eng ko'p yordam berdi.", flag: '🇺🇿' },
        ],
        landingPricingTitle:   'Narxlar',
        landingPricingSub:     'Arzon, lekin kuchli',
        landingPricingPerMo:   'UZS/oy',
        landingPricingPopular: '⭐ Eng mashhur',
        landingFreeFeat: ["✅ 3 ta mock test", "✅ Lug'at moduli", "✅ Statistika", "❌ AI baholash", "❌ Cheksiz testlar"],
        landingPremFeat: ["✅ Cheksiz mock testlar", "✅ AI Writing baholash", "✅ AI Speaking baholash", "✅ Shaxsiy o'quv rejasi", "✅ Telegram bot"],
        landingPricingBtn:  'Boshlash',
        landingCtaTitle:    'Bugun boshlang — bepul!',
        landingCtaSub:      "Ro'yxatdan o'tish 1 daqiqa oladi. Kredit karta kerak emas.",
        landingCtaBtn:      'Hoziroq boshlash →',
    },
    ru: {
        // Navbar
        dashboard:    'Главная',
        vocabulary:   'Словарь',
        statistics:   'Статистика',
        tests:        'Тесты',
        ai:           'AI Репетитор',
        profile:      'Профиль',
        settings:     'Настройки',
        logout:       'Выйти',
        notifications:'Уведомления',
        // Settings
        language:     'Язык',
        save:         'Сохранить',
        saved:        '✅ Настройки сохранены!',
        deleteAcc:    'Удалить аккаунт',
        deleteDesc:   'Это действие необратимо',
        delete:       'Удалить',
        dangerZone:   '⚠️ Опасная зона',
        emailNotif:   'Email уведомления',
        emailDesc:    'О новых тестах и результатах',
        telegramNotif:'Telegram уведомления',
        telegramDesc: 'Получать сообщения через бота',
        dailyReminder:'Ежедневные напоминания',
        dailyDesc:    'Мотивация учиться каждый день',
        // Dashboard
        hello:        'Привет',
        dailyStreak:  'Серия дней',
        streakDays:   'дней подряд',
        dailyGoal:    'Цель на день',
        done:         '✅ Выполнено!',
        remaining:    (n) => `Осталось ${n}`,
        xpUntil:      (n) => `До ${n} XP`,
        maxLevel:     'Макс. уровень! 🏆',
        myResults:    'Мои результаты',
        testsCount:   (n) => `${n} тестов`,
        aiServices:   'AI Сервисы',
        aiTeacher:    'AI Репетитор',
        aiTeacherSub: 'Проверка эссе, практика speaking, грамматика — в любое время',
        startChat:    'Начать чат',
        sections:     'Разделы',
        vocabSub:     'Сохранение и повторение слов',
        statsSub:     'Прогресс и слабые стороны',
        testsSub:     'Начать пробные тесты',
        levelTitles:  ['Новичок', 'Новичок+', 'Средний', 'Продвинутый', 'Эксперт'],
        dailyPlan:    'План на день',
        dailyPlanSub: 'AI составит персональный план',
        // Common
        back:         '← Назад',
        cancel:       'Отмена',
        error:        'Произошла ошибка',
        loading:      'Загрузка...',
        saving:       'Сохранение...',
        noData:       'Данных пока нет',
        // Vocabulary Page
        vocabTitle:   '📚 Словарь',
        wordsCount:   (n) => `${n} слов сохранено`,
        addWord:      '➕ Добавить слово',
        allWords:     (n) => `📖 Все слова (${n})`,
        flashcardTab: '🔄 Флэшкарты',
        searchPlaceholder: '🔍 Поиск по слову или переводу...',
        wordNotFound: 'Не найдено',
        noWordsYet:   'Слов пока нет',
        tryOtherWord: 'Попробуйте другое слово',
        addFirstWord: 'Нажмите "Добавить слово"',
        wordAdded:    '✅ Слово добавлено!',
        wordDeleted:  '🗑️ Слово удалено',
        confirmDelete:'Удалить это слово?',
        errorOccurred:'❌ Произошла ошибка',
        // Flashcard
        flipCard:     'Нажмите — увидите перевод',
        howWell:      'Насколько хорошо вы знаете?',
        clickToFlip:  'нажмите →',
        translation:  'Перевод',
        rateUnknown:  'Не знаю',
        rateHard:     'Сложно',
        rateRemember: 'Вспомнил',
        rateEasy:     'Легко!',
        skipCard:     'Пропустить →',
        reviewDone:   (n) => `${n} слов повторено!`,
        reviewAgain:  '🔄 Снова',
        reviewAll:    '📖 Повторить всё',
        // Review options
        todayReview:  '🔔 Повторение на сегодня',
        todayReviewSub: 'Слова, пришло время повторить по алгоритму SM-2',
        startReview:  (n) => `Начать (${n})`,
        noReviewDue:  'Пока нет слов для повторения',
        reviewAllWords: '📖 Повторить все слова',
        reviewAllSub: 'Учить все слова из словаря в режиме флэшкарт',
        reviewAllBtn: (n) => `Повторить все (${n})`,
        noWordsToReview: 'Слов пока нет',
        // Add word modal
        newWord:      '➕ Новое слово',
        wordEng:      'Слово (английский) *',
        wordTranslation: 'Перевод *',
        exampleSentence: 'Пример предложения (необязательно)',
        wordRequired: 'Слово и перевод обязательны!',
        addError:     'Произошла ошибка. Попробуйте снова.',
        // Statistics Page
        statsTitle:   '📊 Статистика',
        statsSub2:    'Ваш прогресс и слабые стороны',
        overallBand:  'Общий Band Score',
        bySection:    'По разделам',
        weakAreas:    '⚠️ Слабые стороны',
        practiceMore: 'Практикуйтесь больше по следующим разделам:',
        tipLabel:     '💡 Совет:',
        tipText: 'По слабым разделам выполняйте минимум 1 тест в день.',
        noWeakAreas:  'Слабых сторон нет!',
        allAbove6:    'Во всех разделах набрано выше 6.0.',
        noTestsYet:   'Тестов пока не было. Статистика появится после прохождения тестов.',
        lastResults:  '📋 Последние результаты',
        noChartData:  'Данных пока нет',
        testsLabel:   (n) => `${n} тестов`,
        // Tests Page
        mockTests:    'Пробные тесты',
        mockTestsSub: 'Выберите раздел и начните тест',
        startBtn:     'Начать →',
        minutes:      (n) => `${n} минут`,
        questions:    (n) => `${n} вопросов`,
        noTests:      'В этом разделе тестов пока нет',
        testDesc:     'Тест состоит из заданий и вопросов',
        comingSoon:   'Этот раздел скоро появится!',
        // Profile Page
        profileTitle: 'Профиль',
        personalInfo: 'Личные данные',
        editBtn:      '✏️ Редактировать',
        cancelEdit:   'Отмена',
        saveBtn2:     '💾 Сохранить',
        phoneLabel:   'Телефон',
        notEntered:   'Не указан',
        dataSaved:    'Данные сохранены!',
        subscription: 'Подписка',
        freePlan:     '🆓 Бесплатный тариф',
        premiumPlan:  '⭐ Premium тариф',
        limitedFeats: 'Ограниченные возможности',
        allFeats:     'Все возможности открыты',
        upgradePrem:  '⚡ Перейти на Premium',
        // AI Chat Page
        aiQuickTitle: '🚀 Быстрые вопросы',
        aiInfoTitle:  '🤖 AI Репетитор',
        aiInfoText:   'Работает на Claude AI. Отвечает на все вопросы по IELTS.',
        aiClearBtn:   '🗑 Очистить',
        aiChatTitle:  '🎓 AI IELTS Репетитор',
        aiPlaceholder:'Введите вопрос... (Enter — отправить, Shift+Enter — новая строка)',
        aiNewChat:    'Новый чат начат! Чем могу помочь?',
        aiNetError:   '⚠️ Произошла ошибка. Проверьте интернет и попробуйте снова.',
        aiWelcome:    'Привет! Я ваш репетитор IELTS 🎓\n\nВы можете спросить меня:\n• Проверка и советы по эссе Writing\n• Практические вопросы Speaking\n• Объяснение грамматики\n• Критерии оценки IELTS\n• Расширение словарного запаса\n\nНачнём! Чем могу помочь?',
        aiQuick1:     'Дай советы по Writing Task 2',
        aiQuick2:     'Что нужно делать для Band 7?',
        aiQuick3:     'Как подготовиться к Speaking Part 2?',
        aiQuick4:     'Проверь моё эссе',
        // Daily Plan Page
        dpHeroTitle:  "Ваш Персональный Учебный План",
        dpHeroSub:    "AI составит план под ваш уровень и цели.\nВыберите срок и начните.",
        dpSkillLabel: "Направление навыка",
        dpDurLabel:   "Выберите срок плана",
        dpGenBtn:     "AI Составить план",
        dpGenHint:    "Выберите срок плана выше",
        dpLoadTitle:  "AI составляет план...",
        dpLoadSub:    "Готовится план под ваш уровень",
        dpBackBtn:    "← Назад",
        dpAiBadge:    "✦ Создано AI",
        dpTotalTasks: "Всего задач",
        dpEstTime:    "Примерное время",
        dpSkillTypes: "Типов навыков",
        dpTasksTitle: "Список задач",
        dpTasksHint:  "(нажмите, когда выполните ✓)",
        dpNewPlan:    "🔄 Создать новый план",
        dpGoTests:    "📝 Перейти к тестам →",
        dpErrorMsg:   "Ошибка при создании плана. Попробуйте ещё раз.",
        dpDur1Label:  "План на 1 день",
        dpDur1Sub:    "Быстрый и эффективный план на сегодня",
        dpDur2Label:  "План на 1 неделю",
        dpDur2Sub:    "7-дневный пошаговый путь обучения",
        dpDur3Label:  "План на 1 месяц",
        dpDur3Sub:    "Полная программа подготовки к IELTS",
        dpSkillAll:   "Все",
        // AIDailyPlanWidget
        widgetTitle:    "Учебный план на день",
        widgetMorning:  "Утренний план",
        widgetAfternoon:"Дневной план",
        widgetEvening:  "Вечерний план",
        widgetSub:      "AI составит персональный план",
        widgetCompact:  "📋 Создать план",
        // Pricing Page
        pricingTitle:   'Тарифы',
        pricingSubtitle:'Выберите подходящий тариф',
        pricingPopular: '⭐ Популярный',
        pricingPerMonth:'UZS/мес',
        pricingFreeFeatures: [
            '✅ 3 mock-теста',
            '✅ Модуль словаря',
            '✅ Статистика',
            '✅ Telegram бот',
            '❌ AI оценивание',
            '❌ Безлимит тестов',
            '❌ Личный план',
        ],
        pricingPremiumFeatures: [
            '✅ Безлимит mock-тестов',
            '✅ AI оценка Writing',
            '✅ AI оценка Speaking',
            '✅ Личный учебный план',
            '✅ Telegram бот',
            '✅ Статистика и анализ',
            '✅ Модуль словаря',
        ],
        pricingFreeBtn:    'Начать',
        pricingPremiumBtn: 'Получить Premium',
        pricingFaqTitle:   'Частые вопросы',
        pricingFaq: [
            { q: 'Как производится оплата?', a: 'Можно оплатить через Click или Payme.' },
            { q: 'Можно ли отменить подписку?', a: 'Да, можно отменить в любое время.' },
            { q: 'Сколько тестов в бесплатной версии?', a: 'В бесплатной версии доступно 3 mock-теста.' },
        ],
        // Landing Page
        landingNavPricing:  'Тарифы',
        landingNavLogin:    'Войти',
        landingNavRegister: 'Начать бесплатно →',
        landingHeroWords:   ["Band 7+", "Band 8+", "Успех", "Высокий балл"],
        landingHeroTitle:   "— будьте готовы",
        landingHeroSub:     "AI оценивание, mock-тесты, персональный план —\nвсё в одной платформе.",
        landingHeroBtn:     'Начать бесплатно →',
        landingHeroLogin:   'Войти',
        landingStats: [
            { num: '50+', label: 'Активных пользователей' },
            { num: '4',   label: 'Разделов IELTS' },
            { num: 'AI',  label: 'Система оценки' },
            { num: '24/7',label: 'Работает' },
        ],
        landingPathTitle: 'Ваш путь',
        landingPathSub:   'Узнайте, что нужно делать на каждом уровне',
        landingBands: [
            { band: '5.0', label: 'Начальный',    color: '#ef4444' },
            { band: '6.0', label: 'Средний',      color: '#f59e0b' },
            { band: '7.0', label: 'Хороший',      color: '#10b981' },
            { band: '8.0', label: 'Отличный',     color: '#3b82f6' },
            { band: '9.0', label: 'Эксперт',      color: '#8b5cf6' },
        ],
        landingFeatTitle: 'Что вы получаете?',
        landingFeatSub:   'Всё необходимое для достижения цели',
        landingFeatures: [
            { icon: '🧠', title: 'AI Оценивание',  desc: 'Искусственный интеллект для Writing и Speaking' },
            { icon: '📝', title: 'Mock-тесты',     desc: 'Reading, Listening, Writing, Speaking — 4 раздела' },
            { icon: '📊', title: 'Статистика',     desc: 'История band score и анализ слабых мест' },
            { icon: '📅', title: 'Личный план',    desc: 'Индивидуальный учебный план для каждого' },
            { icon: '📚', title: 'Словарь',        desc: 'Запоминание слов методом интервальных повторений' },
            { icon: '🤖', title: 'Telegram Bot',   desc: 'Практикуйтесь где угодно' },
        ],
        landingTestimonialsTitle: 'Что говорят пользователи?',
        landingTestimonials: [
            { name: 'Али Х.',    score: '7.5', text: 'За 3 месяца поднял band с 5.5 до 7.5!',   flag: '🇺🇿' },
            { name: 'Нозима Б.', score: '8.0', text: 'AI feedback очень точный и полезный.',     flag: '🇺🇿' },
            { name: 'Малика Т.', score: '7.0', text: 'Speaking тесты помогли мне больше всего.', flag: '🇺🇿' },
        ],
        landingPricingTitle:   'Тарифы',
        landingPricingSub:     'Доступно, но мощно',
        landingPricingPerMo:   'UZS/мес',
        landingPricingPopular: '⭐ Самый популярный',
        landingFreeFeat: ['✅ 3 mock-теста', '✅ Модуль словаря', '✅ Статистика', '❌ AI оценивание', '❌ Безлимит тестов'],
        landingPremFeat: ['✅ Безлимит mock-тестов', '✅ AI оценка Writing', '✅ AI оценка Speaking', '✅ Личный план', '✅ Telegram бот'],
        landingPricingBtn:  'Начать',
        landingCtaTitle:    'Начните сегодня — бесплатно!',
        landingCtaSub:      'Регистрация займёт 1 минуту. Карта не нужна.',
        landingCtaBtn:      'Начать прямо сейчас →',
    },
    en: {
        // Navbar
        dashboard:    'Dashboard',
        vocabulary:   'Vocabulary',
        statistics:   'Statistics',
        tests:        'Tests',
        ai:           'AI Tutor',
        profile:      'Profile',
        settings:     'Settings',
        logout:       'Log out',
        notifications:'Notifications',
        // Settings
        language:     'Language',
        save:         'Save',
        saved:        '✅ Settings saved!',
        deleteAcc:    'Delete account',
        deleteDesc:   'This action cannot be undone',
        delete:       'Delete',
        dangerZone:   '⚠️ Danger zone',
        emailNotif:   'Email notifications',
        emailDesc:    'About new tests and results',
        telegramNotif:'Telegram notifications',
        telegramDesc: 'Receive messages via bot',
        dailyReminder:'Daily reminders',
        dailyDesc:    'Motivation to study every day',
        // Dashboard
        hello:        'Hello',
        dailyStreak:  'Daily streak',
        streakDays:   'days in a row',
        dailyGoal:    'Daily goal',
        done:         '✅ Done!',
        remaining: (n) => `${n} left`,
        xpUntil: (n) => `Until ${n} XP`,
        maxLevel: 'Max level! 🏆',
        myResults: 'My Results',
        testsCount: (n) => `${n} tests`,
        aiServices:   'AI Services',
        aiTeacher:    'AI Tutor',
        aiTeacherSub: 'Essay review, speaking practice, grammar — anytime, any topic',
        startChat:    'Start chat',
        sections:     'Sections',
        vocabSub:     'Save and review words',
        statsSub:     'Progress and weak areas',
        testsSub:     'Start mock tests',
        levelTitles:  ['Beginner', 'Beginner+', 'Intermediate', 'Advanced', 'Expert'],
        dailyPlan:    'Daily Plan',
        dailyPlanSub: 'AI creates your personal plan',
        // Common
        back:         '← Back',
        cancel:       'Cancel',
        error:        'An error occurred',
        loading:      'Loading...',
        saving:       'Saving...',
        noData:       'No data yet',
        // Vocabulary Page
        vocabTitle:   '📚 Vocabulary',
        wordsCount:   (n) => `${n} words saved`,
        addWord:      '➕ Add word',
        allWords:     (n) => `📖 All words (${n})`,
        flashcardTab: '🔄 Flashcards',
        searchPlaceholder: '🔍 Search by word or translation...',
        wordNotFound: 'Not found',
        noWordsYet:   'No words yet',
        tryOtherWord: 'Try a different word',
        addFirstWord: 'Click "Add word" to get started',
        wordAdded:    '✅ Word added!',
        wordDeleted:  '🗑️ Word deleted',
        confirmDelete:'Delete this word?',
        errorOccurred:'❌ An error occurred',
        // Flashcard
        flipCard:     'Tap card to see translation',
        howWell:      'How well did you know it?',
        clickToFlip:  'tap →',
        translation:  'Translation',
        rateUnknown:  "Didn't know",
        rateHard:     'Hard',
        rateRemember: 'Got it',
        rateEasy:     'Easy!',
        skipCard:     'Skip →',
        reviewDone:   (n) => `${n} words reviewed!`,
        reviewAgain:  '🔄 Again',
        reviewAll:    '📖 Review all',
        // Review options
        todayReview:  '🔔 Today\'s review',
        todayReviewSub: 'Words due for review by the SM-2 algorithm',
        startReview:  (n) => `Start (${n})`,
        noReviewDue:  'No words due right now',
        reviewAllWords: '📖 Review all words',
        reviewAllSub: 'Study all vocabulary words as flashcards',
        reviewAllBtn: (n) => `Review all (${n})`,
        noWordsToReview: 'No words yet',
        // Add word modal
        newWord:      '➕ New word',
        wordEng:      'Word (English) *',
        wordTranslation: 'Translation *',
        exampleSentence: 'Example sentence (optional)',
        wordRequired: 'Word and translation are required!',
        addError:     'An error occurred. Please try again.',
        // Statistics Page
        statsTitle:   '📊 Statistics',
        statsSub2:    'Your progress and weak areas',
        overallBand:  'Overall Band Score',
        bySection:    'By section',
        weakAreas:    '⚠️ Weak areas',
        practiceMore: 'Practice more on the following sections:',
        tipLabel:     '💡 Tip:',
        tipText:      'Do at least 1 test per day for weak sections.',
        noWeakAreas:  'No weak areas!',
        allAbove6:    'You scored above 6.0 in all sections.',
        noTestsYet:   'No tests taken yet. Statistics will appear after completing tests.',
        lastResults:  '📋 Recent results',
        noChartData:  'No data yet',
        testsLabel:   (n) => `${n} tests`,
        // Tests Page
        mockTests:    'Mock Tests',
        mockTestsSub: 'Choose a section and start the test',
        startBtn:     'Start →',
        minutes:      (n) => `${n} minutes`,
        questions:    (n) => `${n} questions`,
        noTests:      'No tests in this section yet',
        testDesc:     'Test consists of tasks and questions',
        comingSoon:   'This section is coming soon!',
        // Profile Page
        profileTitle: 'Profile',
        personalInfo: 'Personal information',
        editBtn:      '✏️ Edit',
        cancelEdit:   'Cancel',
        saveBtn2:     '💾 Save',
        phoneLabel:   'Phone',
        notEntered:   'Not provided',
        dataSaved:    'Information saved!',
        subscription: 'Subscription',
        freePlan:     '🆓 Free plan',
        premiumPlan:  '⭐ Premium plan',
        limitedFeats: 'Limited features',
        allFeats:     'All features unlocked',
        upgradePrem:  '⚡ Upgrade to Premium',
        // AI Chat Page
        aiQuickTitle: '🚀 Quick prompts',
        aiInfoTitle:  '🤖 AI Tutor',
        aiInfoText:   'Powered by Claude AI. Answers all IELTS questions.',
        aiClearBtn:   '🗑 Clear',
        aiChatTitle:  '🎓 AI IELTS Tutor',
        aiPlaceholder:'Type your question... (Enter — send, Shift+Enter — new line)',
        aiNewChat:    'New chat started! How can I help?',
        aiNetError:   '⚠️ An error occurred. Check your internet and try again.',
        aiWelcome:    "Hello! I'm your IELTS tutor 🎓\n\nYou can ask me about:\n• Writing essay review and tips\n• Speaking practice questions\n• Grammar explanations\n• IELTS band scoring criteria\n• Vocabulary building\n\nLet's get started! How can I help?",
        aiQuick1:     'Give me tips for Writing Task 2',
        aiQuick2:     'What do I need to do to get Band 7?',
        aiQuick3:     'How to prepare for Speaking Part 2?',
        aiQuick4:     'Check my essay',
        // Daily Plan Page
        dpHeroTitle:  "Your Personal Study Plan",
        dpHeroSub:    "AI will create a targeted plan matched to your level.\nChoose a duration and get started.",
        dpSkillLabel: "Skill Focus",
        dpDurLabel:   "Choose Plan Duration",
        dpGenBtn:     "Generate AI Plan",
        dpGenHint:    "Select a duration above to generate your plan",
        dpLoadTitle:  "AI is building your plan...",
        dpLoadSub:    "Preparing a plan tailored to your level",
        dpBackBtn:    "← Back",
        dpAiBadge:    "✦ Generated by AI",
        dpTotalTasks: "Total tasks",
        dpEstTime:    "Est. time",
        dpSkillTypes: "Skill types",
        dpTasksTitle: "Task list",
        dpTasksHint:  "(tap when done ✓)",
        dpNewPlan:    "🔄 Generate new plan",
        dpGoTests:    "📝 Go to tests →",
        dpErrorMsg:   "Failed to create plan. Please try again.",
        dpDur1Label:  "1-Day Plan",
        dpDur1Sub:    "Quick and effective plan for today",
        dpDur2Label:  "1-Week Plan",
        dpDur2Sub:    "7-day step-by-step learning path",
        dpDur3Label:  "1-Month Plan",
        dpDur3Sub:    "Full IELTS preparation program",
        dpSkillAll:   "All",
        // AIDailyPlanWidget
        widgetTitle:    "Daily Study Plan",
        widgetMorning:  "Morning plan",
        widgetAfternoon:"Afternoon plan",
        widgetEvening:  "Evening plan",
        widgetSub:      "AI creates your personal plan",
        widgetCompact:  "📋 Create plan",
        // Pricing Page
        pricingTitle:   'Pricing',
        pricingSubtitle:'Choose the plan that fits your goals',
        pricingPopular: '⭐ Popular',
        pricingPerMonth:'UZS/mo',
        pricingFreeFeatures: [
            '✅ 3 mock tests',
            '✅ Vocabulary module',
            '✅ Statistics',
            '✅ Telegram bot',
            '❌ AI grading',
            '❌ Unlimited tests',
            '❌ Personal plan',
        ],
        pricingPremiumFeatures: [
            '✅ Unlimited mock tests',
            '✅ AI Writing grading',
            '✅ AI Speaking grading',
            '✅ Personal study plan',
            '✅ Telegram bot',
            '✅ Statistics & analysis',
            '✅ Vocabulary module',
        ],
        pricingFreeBtn:    'Get started',
        pricingPremiumBtn: 'Get Premium',
        pricingFaqTitle:   'Frequently asked questions',
        pricingFaq: [
            { q: 'How do I pay?', a: 'You can pay via Click or Payme.' },
            { q: 'Can I cancel my subscription?', a: 'Yes, you can cancel at any time.' },
            { q: 'How many tests are in the free version?', a: 'The free version includes 3 mock tests.' },
        ],
        // Landing Page
        landingNavPricing:  'Pricing',
        landingNavLogin:    'Log in',
        landingNavRegister: 'Start free →',
        landingHeroWords:   ["Band 7+", "Band 8+", "Success", "Top score"],
        landingHeroTitle:   "— get ready for IELTS",
        landingHeroSub:     "AI grading, mock tests, personal study plan —\nall in one platform.",
        landingHeroBtn:     'Start free →',
        landingHeroLogin:   'Log in',
        landingStats: [
            { num: '50+', label: 'Active users' },
            { num: '4',   label: 'IELTS sections' },
            { num: 'AI',  label: 'Grading system' },
            { num: '24/7',label: 'Always on' },
        ],
        landingPathTitle: 'Your roadmap',
        landingPathSub:   'Find out what to focus on at every level',
        landingBands: [
            { band: '5.0', label: 'Beginner',     color: '#ef4444' },
            { band: '6.0', label: 'Intermediate', color: '#f59e0b' },
            { band: '7.0', label: 'Good',         color: '#10b981' },
            { band: '8.0', label: 'Excellent',    color: '#3b82f6' },
            { band: '9.0', label: 'Expert',       color: '#8b5cf6' },
        ],
        landingFeatTitle: 'What do you get?',
        landingFeatSub:   'Everything you need to reach your goal',
        landingFeatures: [
            { icon: '🧠', title: 'AI Grading',     desc: 'Artificial intelligence grading for Writing & Speaking' },
            { icon: '📝', title: 'Mock Tests',     desc: 'Reading, Listening, Writing, Speaking — 4 sections' },
            { icon: '📊', title: 'Statistics',     desc: 'Band score history and weak-area analysis' },
            { icon: '📅', title: 'Personal Plan',  desc: 'Individual study plan for every user' },
            { icon: '📚', title: 'Vocabulary',     desc: 'Word memorisation with spaced repetition' },
            { icon: '🤖', title: 'Telegram Bot',   desc: 'Practice anywhere, anytime' },
        ],
        landingTestimonialsTitle: 'What users say',
        landingTestimonials: [
            { name: 'Ali X.',     score: '7.5', text: 'Raised my band from 5.5 to 7.5 in 3 months!',  flag: '🇺🇿' },
            { name: 'Nozima B.', score: '8.0', text: 'The AI feedback was very precise and helpful.', flag: '🇺🇿' },
            { name: 'Malika T.', score: '7.0', text: 'Speaking tests helped me the most.',            flag: '🇺🇿' },
        ],
        landingPricingTitle:   'Pricing',
        landingPricingSub:     'Affordable, but powerful',
        landingPricingPerMo:   'UZS/mo',
        landingPricingPopular: '⭐ Most popular',
        landingFreeFeat: ['✅ 3 mock tests', '✅ Vocabulary module', '✅ Statistics', '❌ AI grading', '❌ Unlimited tests'],
        landingPremFeat: ['✅ Unlimited mock tests', '✅ AI Writing grading', '✅ AI Speaking grading', '✅ Personal plan', '✅ Telegram bot'],
        landingPricingBtn:  'Get started',
        landingCtaTitle:    'Start today — for free!',
        landingCtaSub:      'Registration takes 1 minute. No credit card needed.',
        landingCtaBtn:      'Start right now →',
    },
};