import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
    const [lang, setLang] = useState(localStorage.getItem('app_language') || 'uz');

    const changeLang = (newLang) => {
        localStorage.setItem('app_language', newLang);
        setLang(newLang);
    };

    return (
        <LanguageContext.Provider value={{ lang, changeLang }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLang() {
    return useContext(LanguageContext);
}

export const translations = {
    uz: {
        // Navbar
        dashboard:    'Dashboard',
        vocabulary:   "Lug'at",
        statistics:   'Statistika',
        tests:        'Testlar',
        ai:           'AI Tutor',
        profile:      'Profil',
        settings:     'Sozlamalar',
        logout:       'Chiqish',
        notifications:'Bildirishnomalar',
        // Settings
        language:     'Til',
        save:         'Saqlash',
        saved:        '✅ Sozlamalar saqlandi!',
        deleteAcc:    "Akkauntni o'chirish",
        deleteDesc:   "Bu amalni qaytarib bo'lmaydi",
        delete:       "O'chirish",
        dangerZone:   '⚠️ Xavfli zona',
        emailNotif:   'Email bildirishnomalar',
        emailDesc:    'Yangi testlar va natijalar haqida',
        telegramNotif:'Telegram bildirishnomalar',
        telegramDesc: 'Bot orqali xabar olish',
        dailyReminder:'Kunlik eslatmalar',
        dailyDesc:    "Har kuni o'qishga undash",
        // Dashboard
        hello:        'Salom',
        dailyStreak:  'Kunlik streak',
        streakDays:   'kun ketma-ket',
        dailyGoal:    'Kunlik maqsad',
        done:         '✅ Bajarildi!',
        remaining:    (n) => `${n} ta qoldi`,
        xpUntil:      (n) => `${n} XP gacha`,
        maxLevel:     'Max level! 🏆',
        myResults:    'Natijalarim',
        testsCount:   (n) => `${n} ta test`,
        aiServices:   'AI Xizmatlar',
        aiTeacher:    'AI Muallim',
        aiTeacherSub: 'Essay tekshiruv, speaking mashq, grammatika — istalgan vaqt istalgan mavzu',
        startChat:    'Suhbat boshlash',
        sections:     "Bo'limlar",
        vocabSub:     "So'zlarni saqlash va takrorlash",
        statsSub:     'Progress va zaif tomonlar',
        testsSub:     'Mock testlarni boshlash',
        levelTitles:  ['Beginner', 'Beginner+', 'Intermediate', 'Advanced', 'Expert'],
        dailyPlan:    'Kunlik Reja',
        dailyPlanSub: "AI sizga shaxsiy reja tuzadi",
        // Common
        back:         '← Orqaga',
        cancel:       'Bekor qilish',
        error:        'Xatolik yuz berdi',
        loading:      'Yuklanmoqda...',
        saving:       'Saqlanmoqda...',
        noData:       "Hali ma'lumot yo'q",
        // Vocabulary Page
        vocabTitle:   "📚 Lug'at",
        wordsCount:   (n) => `${n} ta so'z saqlangan`,
        addWord:      "➕ So'z qo'shish",
        allWords:     (n) => `📖 Barcha so'zlar (${n})`,
        flashcardTab: '🔄 Flashcard',
        searchPlaceholder: "🔍 So'z yoki tarjima bo'yicha qidirish...",
        wordNotFound: 'Topilmadi',
        noWordsYet:   "Hali so'z yo'q",
        tryOtherWord: 'Boshqa so\'z bilan qidiring',
        addFirstWord: '"So\'z qo\'shish" tugmasini bosing',
        wordAdded:    "✅ So'z qo'shildi!",
        wordDeleted:  "🗑️ So'z o'chirildi",
        confirmDelete:"Bu so'zni o'chirishni istaysizmi?",
        errorOccurred:'❌ Xatolik yuz berdi',
        // Flashcard
        flipCard:     "Kartani bosing — tarjimani ko'ring",
        howWell:      'Qanchalik yaxshi bildingiz?',
        clickToFlip:  'bosing →',
        translation:  'Tarjima',
        rateUnknown:  'Bilmadim',
        rateHard:     'Qiyin',
        rateRemember: 'Esladim',
        rateEasy:     'Oson!',
        skipCard:     "O'tkazib yuborish →",
        reviewDone:   (n) => `${n} ta so'z takrorlandi!`,
        reviewAgain:  '🔄 Qaytadan',
        reviewAll:    "📖 Hammasini takrorla",
        // Review options
        todayReview:  '🔔 Bugungi takrorlash',
        todayReviewSub: "SM-2 algoritmi bo'yicha takrorlash vaqti kelgan so'zlar",
        startReview:  (n) => `Boshlash (${n} ta)`,
        noReviewDue:  "Hozircha tayyor so'z yo'q",
        reviewAllWords: "📖 Barcha so'zlarni takrorlash",
        reviewAllSub: "Lug'atdagi barcha so'zlarni flashcard sifatida o'rganish",
        reviewAllBtn: (n) => `Hammasini takrorla (${n} ta)`,
        noWordsToReview: "Hali so'z yo'q",
        // Add word modal
        newWord:      '➕ Yangi so\'z',
        wordEng:      "So'z (inglizcha) *",
        wordTranslation: 'Tarjima *',
        exampleSentence: 'Misol jumla (ixtiyoriy)',
        wordRequired: "So'z va tarjima majburiy!",
        addError:     "Xatolik yuz berdi. Qaytadan urinib ko'ring.",
        // Statistics Page
        statsTitle:   '📊 Statistika',
        statsSub2:    'Progressingiz va zaif tomonlaringiz',
        overallBand:  'Umumiy Band Score',
        bySection:    "Bo'limlar bo'yicha",
        weakAreas:    '⚠️ Zaif tomonlar',
        practiceMore: "Quyidagi bo'limlar bo'yicha ko'proq mashq qiling:",
        tipLabel:     '💡 Tavsiya:',
        tipText:      "Zaif bo'limlar bo'yicha kunida kamida 1 ta test ishlang.",
        noWeakAreas:  "Zaif tomonlar yo'q!",
        allAbove6:    "Barcha bo'limlarda 6.0 dan yuqori ball to'plangansiz.",
        noTestsYet:   'Hali hech qanday test topshirilmagan. Statistika test ishlangandan keyin ko\'rinadi.',
        lastResults:  "📋 So'nggi natijalar",
        noChartData:  "Hali ma'lumot yo'q",
        testsLabel:   (n) => `${n} ta test`,
        // Tests Page
        mockTests:    'Mock Testlar',
        mockTestsSub: "Bo'limni tanlang va testni boshlang",
        startBtn:     'Boshlash →',
        minutes:      (n) => `${n} daqiqa`,
        questions:    (n) => `${n} savol`,
        noTests:      "Bu bo'limda hali testlar yo'q",
        testDesc:     'Test topshiriq va savollardan iborat',
        comingSoon:   "Bu bo'lim tez orada qo'shiladi!",
        // Profile Page
        profileTitle: 'Profil',
        personalInfo: "Shaxsiy ma'lumotlar",
        editBtn:      '✏️ Tahrirlash',
        cancelEdit:   'Bekor qilish',
        saveBtn2:     '💾 Saqlash',
        phoneLabel:   'Telefon',
        notEntered:   'Kiritilmagan',
        dataSaved:    "Ma'lumotlar saqlandi!",
        subscription: 'Obuna',
        freePlan:     '🆓 Bepul tarif',
        premiumPlan:  '⭐ Premium tarif',
        limitedFeats: 'Cheklangan imkoniyatlar',
        allFeats:     'Barcha imkoniyatlar ochiq',
        upgradePrem:  "⚡ Premium ga o'tish",
        // AI Chat Page
        aiQuickTitle: '🚀 Tezkor savollar',
        aiInfoTitle:  '🤖 AI Tutor',
        aiInfoText:   "Claude AI asosida ishlaydi. IELTS bo'yicha barcha savollarga javob beradi.",
        aiClearBtn:   '🗑 Tozalash',
        aiChatTitle:  '🎓 AI IELTS Tutor',
        aiPlaceholder:"Savolingizni yozing... (Enter — yuborish, Shift+Enter — yangi qator)",
        aiNewChat:    'Yangi suhbat boshlandi! Qanday yordam kerak?',
        aiNetError:   "⚠️ Xatolik yuz berdi. Internet aloqangizni tekshiring va qayta urinib ko'ring.",
        aiWelcome:    "Salom! Men sizning IELTS tutoryingizman 🎓\n\nMenga quyidagilarni so'rashingiz mumkin:\n• Writing esse tekshiruv va maslahatlar\n• Speaking mashq savollari\n• Grammatika tushuntirish\n• IELTS band scoring mezonlari\n• Vocabulary kengaytirish\n\nBoshlaylik! Qanday yordam kerak?",
        aiQuick1:     'Writing Task 2 uchun maslahat ber',
        aiQuick2:     'Band 7 olish uchun nima qilish kerak?',
        aiQuick3:     'Speaking Part 2 qanday tayyorlaniladi?',
        aiQuick4:     'Mening esseni tekshir',
    },
    ru: {
        // Navbar
        dashboard:    'Главная',
        vocabulary:   'Словарь',
        statistics:   'Статистика',
        tests:        'Тесты',
        ai:           'AI Репетитор',
        profile:      'Профиль',
        settings:     'Настройки',
        logout:       'Выйти',
        notifications:'Уведомления',
        // Settings
        language:     'Язык',
        save:         'Сохранить',
        saved:        '✅ Настройки сохранены!',
        deleteAcc:    'Удалить аккаунт',
        deleteDesc:   'Это действие необратимо',
        delete:       'Удалить',
        dangerZone:   '⚠️ Опасная зона',
        emailNotif:   'Email уведомления',
        emailDesc:    'О новых тестах и результатах',
        telegramNotif:'Telegram уведомления',
        telegramDesc: 'Получать сообщения через бота',
        dailyReminder:'Ежедневные напоминания',
        dailyDesc:    'Мотивация учиться каждый день',
        // Dashboard
        hello:        'Привет',
        dailyStreak:  'Серия дней',
        streakDays:   'дней подряд',
        dailyGoal:    'Цель на день',
        done:         '✅ Выполнено!',
        remaining:    (n) => `Осталось ${n}`,
        xpUntil:      (n) => `До ${n} XP`,
        maxLevel:     'Макс. уровень! 🏆',
        myResults:    'Мои результаты',
        testsCount:   (n) => `${n} тестов`,
        aiServices:   'AI Сервисы',
        aiTeacher:    'AI Репетитор',
        aiTeacherSub: 'Проверка эссе, практика speaking, грамматика — в любое время',
        startChat:    'Начать чат',
        sections:     'Разделы',
        vocabSub:     'Сохранение и повторение слов',
        statsSub:     'Прогресс и слабые стороны',
        testsSub:     'Начать пробные тесты',
        levelTitles:  ['Новичок', 'Новичок+', 'Средний', 'Продвинутый', 'Эксперт'],
        dailyPlan:    'План на день',
        dailyPlanSub: 'AI составит персональный план',
        // Common
        back:         '← Назад',
        cancel:       'Отмена',
        error:        'Произошла ошибка',
        loading:      'Загрузка...',
        saving:       'Сохранение...',
        noData:       'Данных пока нет',
        // Vocabulary Page
        vocabTitle:   '📚 Словарь',
        wordsCount:   (n) => `${n} слов сохранено`,
        addWord:      '➕ Добавить слово',
        allWords:     (n) => `📖 Все слова (${n})`,
        flashcardTab: '🔄 Флэшкарты',
        searchPlaceholder: '🔍 Поиск по слову или переводу...',
        wordNotFound: 'Не найдено',
        noWordsYet:   'Слов пока нет',
        tryOtherWord: 'Попробуйте другое слово',
        addFirstWord: 'Нажмите "Добавить слово"',
        wordAdded:    '✅ Слово добавлено!',
        wordDeleted:  '🗑️ Слово удалено',
        confirmDelete:'Удалить это слово?',
        errorOccurred:'❌ Произошла ошибка',
        // Flashcard
        flipCard:     'Нажмите — увидите перевод',
        howWell:      'Насколько хорошо вы знаете?',
        clickToFlip:  'нажмите →',
        translation:  'Перевод',
        rateUnknown:  'Не знаю',
        rateHard:     'Сложно',
        rateRemember: 'Вспомнил',
        rateEasy:     'Легко!',
        skipCard:     'Пропустить →',
        reviewDone:   (n) => `${n} слов повторено!`,
        reviewAgain:  '🔄 Снова',
        reviewAll:    '📖 Повторить всё',
        // Review options
        todayReview:  '🔔 Повторение на сегодня',
        todayReviewSub: 'Слова, пришло время повторить по алгоритму SM-2',
        startReview:  (n) => `Начать (${n})`,
        noReviewDue:  'Пока нет слов для повторения',
        reviewAllWords: '📖 Повторить все слова',
        reviewAllSub: 'Учить все слова из словаря в режиме флэшкарт',
        reviewAllBtn: (n) => `Повторить все (${n})`,
        noWordsToReview: 'Слов пока нет',
        // Add word modal
        newWord:      '➕ Новое слово',
        wordEng:      'Слово (английский) *',
        wordTranslation: 'Перевод *',
        exampleSentence: 'Пример предложения (необязательно)',
        wordRequired: 'Слово и перевод обязательны!',
        addError:     'Произошла ошибка. Попробуйте снова.',
        // Statistics Page
        statsTitle:   '📊 Статистика',
        statsSub2:    'Ваш прогресс и слабые стороны',
        overallBand:  'Общий Band Score',
        bySection:    'По разделам',
        weakAreas:    '⚠️ Слабые стороны',
        practiceMore: 'Практикуйтесь больше по следующим разделам:',
        tipLabel:     '💡 Совет:',
        tipText:      'По слабым разделам выполняйте минимум 1 тест в день.',
        noWeakAreas:  'Слабых сторон нет!',
        allAbove6:    'Во всех разделах набрано выше 6.0.',
        noTestsYet:   'Тестов пока не было. Статистика появится после прохождения тестов.',
        lastResults:  '📋 Последние результаты',
        noChartData:  'Данных пока нет',
        testsLabel:   (n) => `${n} тестов`,
        // Tests Page
        mockTests:    'Пробные тесты',
        mockTestsSub: 'Выберите раздел и начните тест',
        startBtn:     'Начать →',
        minutes:      (n) => `${n} минут`,
        questions:    (n) => `${n} вопросов`,
        noTests:      'В этом разделе тестов пока нет',
        testDesc:     'Тест состоит из заданий и вопросов',
        comingSoon:   'Этот раздел скоро появится!',
        // Profile Page
        profileTitle: 'Профиль',
        personalInfo: 'Личные данные',
        editBtn:      '✏️ Редактировать',
        cancelEdit:   'Отмена',
        saveBtn2:     '💾 Сохранить',
        phoneLabel:   'Телефон',
        notEntered:   'Не указан',
        dataSaved:    'Данные сохранены!',
        subscription: 'Подписка',
        freePlan:     '🆓 Бесплатный тариф',
        premiumPlan:  '⭐ Premium тариф',
        limitedFeats: 'Ограниченные возможности',
        allFeats:     'Все возможности открыты',
        upgradePrem:  '⚡ Перейти на Premium',
        // AI Chat Page
        aiQuickTitle: '🚀 Быстрые вопросы',
        aiInfoTitle:  '🤖 AI Репетитор',
        aiInfoText:   'Работает на Claude AI. Отвечает на все вопросы по IELTS.',
        aiClearBtn:   '🗑 Очистить',
        aiChatTitle:  '🎓 AI IELTS Репетитор',
        aiPlaceholder:'Введите вопрос... (Enter — отправить, Shift+Enter — новая строка)',
        aiNewChat:    'Новый чат начат! Чем могу помочь?',
        aiNetError:   '⚠️ Произошла ошибка. Проверьте интернет и попробуйте снова.',
        aiWelcome:    'Привет! Я ваш репетитор IELTS 🎓\n\nВы можете спросить меня:\n• Проверка и советы по эссе Writing\n• Практические вопросы Speaking\n• Объяснение грамматики\n• Критерии оценки IELTS\n• Расширение словарного запаса\n\nНачнём! Чем могу помочь?',
        aiQuick1:     'Дай советы по Writing Task 2',
        aiQuick2:     'Что нужно делать для Band 7?',
        aiQuick3:     'Как подготовиться к Speaking Part 2?',
        aiQuick4:     'Проверь моё эссе',
    },
    en: {
        // Navbar
        dashboard:    'Dashboard',
        vocabulary:   'Vocabulary',
        statistics:   'Statistics',
        tests:        'Tests',
        ai:           'AI Tutor',
        profile:      'Profile',
        settings:     'Settings',
        logout:       'Log out',
        notifications:'Notifications',
        // Settings
        language:     'Language',
        save:         'Save',
        saved:        '✅ Settings saved!',
        deleteAcc:    'Delete account',
        deleteDesc:   'This action cannot be undone',
        delete:       'Delete',
        dangerZone:   '⚠️ Danger zone',
        emailNotif:   'Email notifications',
        emailDesc:    'About new tests and results',
        telegramNotif:'Telegram notifications',
        telegramDesc: 'Receive messages via bot',
        dailyReminder:'Daily reminders',
        dailyDesc:    'Motivation to study every day',
        // Dashboard
        hello:        'Hello',
        dailyStreak:  'Daily streak',
        streakDays:   'days in a row',
        dailyGoal:    'Daily goal',
        done:         '✅ Done!',
        remaining:    (n) => `${n} left`,
        xpUntil:      (n) => `Until ${n} XP`,
        maxLevel:     'Max level! 🏆',
        myResults:    'My Results',
        testsCount:   (n) => `${n} tests`,
        aiServices:   'AI Services',
        aiTeacher:    'AI Tutor',
        aiTeacherSub: 'Essay review, speaking practice, grammar — anytime, any topic',
        startChat:    'Start chat',
        sections:     'Sections',
        vocabSub:     'Save and review words',
        statsSub:     'Progress and weak areas',
        testsSub:     'Start mock tests',
        levelTitles:  ['Beginner', 'Beginner+', 'Intermediate', 'Advanced', 'Expert'],
        dailyPlan:    'Daily Plan',
        dailyPlanSub: 'AI creates your personal plan',
        // Common
        back:         '← Back',
        cancel:       'Cancel',
        error:        'An error occurred',
        loading:      'Loading...',
        saving:       'Saving...',
        noData:       'No data yet',
        // Vocabulary Page
        vocabTitle:   '📚 Vocabulary',
        wordsCount:   (n) => `${n} words saved`,
        addWord:      '➕ Add word',
        allWords:     (n) => `📖 All words (${n})`,
        flashcardTab: '🔄 Flashcards',
        searchPlaceholder: '🔍 Search by word or translation...',
        wordNotFound: 'Not found',
        noWordsYet:   'No words yet',
        tryOtherWord: 'Try a different word',
        addFirstWord: 'Click "Add word" to get started',
        wordAdded:    '✅ Word added!',
        wordDeleted:  '🗑️ Word deleted',
        confirmDelete:'Delete this word?',
        errorOccurred:'❌ An error occurred',
        // Flashcard
        flipCard:     'Tap card to see translation',
        howWell:      'How well did you know it?',
        clickToFlip:  'tap →',
        translation:  'Translation',
        rateUnknown:  "Didn't know",
        rateHard:     'Hard',
        rateRemember: 'Got it',
        rateEasy:     'Easy!',
        skipCard:     'Skip →',
        reviewDone:   (n) => `${n} words reviewed!`,
        reviewAgain:  '🔄 Again',
        reviewAll:    '📖 Review all',
        // Review options
        todayReview:  '🔔 Today\'s review',
        todayReviewSub: 'Words due for review by the SM-2 algorithm',
        startReview:  (n) => `Start (${n})`,
        noReviewDue:  'No words due right now',
        reviewAllWords: '📖 Review all words',
        reviewAllSub: 'Study all vocabulary words as flashcards',
        reviewAllBtn: (n) => `Review all (${n})`,
        noWordsToReview: 'No words yet',
        // Add word modal
        newWord:      '➕ New word',
        wordEng:      'Word (English) *',
        wordTranslation: 'Translation *',
        exampleSentence: 'Example sentence (optional)',
        wordRequired: 'Word and translation are required!',
        addError:     'An error occurred. Please try again.',
        // Statistics Page
        statsTitle:   '📊 Statistics',
        statsSub2:    'Your progress and weak areas',
        overallBand:  'Overall Band Score',
        bySection:    'By section',
        weakAreas:    '⚠️ Weak areas',
        practiceMore: 'Practice more on the following sections:',
        tipLabel:     '💡 Tip:',
        tipText:      'Do at least 1 test per day for weak sections.',
        noWeakAreas:  'No weak areas!',
        allAbove6:    'You scored above 6.0 in all sections.',
        noTestsYet:   'No tests taken yet. Statistics will appear after completing tests.',
        lastResults:  '📋 Recent results',
        noChartData:  'No data yet',
        testsLabel:   (n) => `${n} tests`,
        // Tests Page
        mockTests:    'Mock Tests',
        mockTestsSub: 'Choose a section and start the test',
        startBtn:     'Start →',
        minutes:      (n) => `${n} minutes`,
        questions:    (n) => `${n} questions`,
        noTests:      'No tests in this section yet',
        testDesc:     'Test consists of tasks and questions',
        comingSoon:   'This section is coming soon!',
        // Profile Page
        profileTitle: 'Profile',
        personalInfo: 'Personal information',
        editBtn:      '✏️ Edit',
        cancelEdit:   'Cancel',
        saveBtn2:     '💾 Save',
        phoneLabel:   'Phone',
        notEntered:   'Not provided',
        dataSaved:    'Information saved!',
        subscription: 'Subscription',
        freePlan:     '🆓 Free plan',
        premiumPlan:  '⭐ Premium plan',
        limitedFeats: 'Limited features',
        allFeats:     'All features unlocked',
        upgradePrem:  '⚡ Upgrade to Premium',
        // AI Chat Page
        aiQuickTitle: '🚀 Quick prompts',
        aiInfoTitle:  '🤖 AI Tutor',
        aiInfoText:   'Powered by Claude AI. Answers all IELTS questions.',
        aiClearBtn:   '🗑 Clear',
        aiChatTitle:  '🎓 AI IELTS Tutor',
        aiPlaceholder:'Type your question... (Enter — send, Shift+Enter — new line)',
        aiNewChat:    'New chat started! How can I help?',
        aiNetError:   '⚠️ An error occurred. Check your internet and try again.',
        aiWelcome:    "Hello! I'm your IELTS tutor 🎓\n\nYou can ask me about:\n• Writing essay review and tips\n• Speaking practice questions\n• Grammar explanations\n• IELTS band scoring criteria\n• Vocabulary building\n\nLet's get started! How can I help?",
        aiQuick1:     'Give me tips for Writing Task 2',
        aiQuick2:     'What do I need to do to get Band 7?',
        aiQuick3:     'How to prepare for Speaking Part 2?',
        aiQuick4:     'Check my essay',
    },
};